### ISSUE TITLE
🚩 Roadmap & Milestones for 2020

### ISSUE THREAD

**Issue by suranah** [practical-nlp/practical-nlp#14]
# 🚩 Overview

Based on the feedback received from the readers, we have decided to focus on a few things to this repo as accessible and useful as possible. This issue contains a high level for the updates planned in 2020. It will continue being updated based on reader feedback. 

# 🛣️  Roadmap

We think the following features, enhancements & fixes are most relevant for 2020:

- [ ] Easy data download for Windows
- [ ] Python & dependencies issues resolved for Windows
- [ ] Full support for running on Collab
- [ ] RASA chatbot notebook
- [ ] Input sample & stats demonstrated for all notebooks
- [ ] Output sample demonstrated for all notebooks
- [ ] Output visualization demonstrated where possible

**Comment by suranah** [comment]
As multiple print buyers had raised the issue on some figures not being legible, we will be adding all color images for anyone to access it.
