### ISSUE TITLE
Fix Dependency Issues and Update code with latest versions of python libraries for Notebooks of Chapter 5

### ISSUE THREAD

**Issue by Ethan0456** [practical-nlp/practical-nlp#148]
I'm working on updating the code for Chapter 5 to ensure compatibility with newer versions of Python and updated libraries. This issue will track the progress and changes made for this specific notebook.

**Notebooks:**
- [ ] 01_KPE.ipynb
- [ ] 02_NERTraining.ipynb
- [ ] 03_NERIssues.ipynb
- [ ] 04_NER_using_spaCy - CoNLL.ipynb
- [ ] 05_BERT_CONLL_NER.ipynb
- [ ] 06_EntityLinking-AzureTextAnalytics.ipynb
- [ ] 07_REWatson.ipynb
- [ ] 08_Duckling.ipynb

**Tasks:**

- [x] Update Python version from 3.6 to 3.9
- [x] Update Ubuntu version to 22.04
- [x] Update all Python libraries to their latest versions
- [x] Test the notebook to ensure it runs without errors

**Context:**
- **Current Python Version:** 3.6
- **Current Ubuntu Version:** 16.04
- **Current Library Versions:**

**Proposed Changes:**
- Update notebooks to run with Ubuntu 22.04
- Update notebooks to run with Python 3.10
- Libraries from each notebooks will be updated to latest version
- Markdown Text will be improved

**Related Issues:**
- Will list them here

Let's work together to update this notebook effectively and ensure it aligns with the latest Python and library versions.
